# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-30 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170630_1832'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WikiLink',
            new_name='WikiUrl',
        ),
    ]
