# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170630_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonCache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('json', models.TimeField()),
            ],
        ),
    ]
