# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_jsoncache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncache',
            name='json',
            field=models.TextField(),
        ),
    ]
