# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20170714_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonCacheData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageid', models.IntegerField(unique=True)),
                ('json', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JsonCacheUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('cache', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.JsonCache')),
            ],
        ),
    ]
