# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-15 15:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_jsoncachedata_jsoncacheurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jsoncacheurl',
            name='cache',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.JsonCacheData'),
        ),
    ]
