"""
Django settings for wikipaths_server project.

Generated by 'django-admin startproject' using Django 1.10.5.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


if "WIKIPATHS_PRODUCTION" in os.environ:
    PRODUCTION_ENV = True
else:
    PRODUCTION_ENV = False



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'wuj9&#z1zi7@!om!@rlumu1#ok#g0wpuke+8^$f6h=$0hfs9ui'

# SECURITY WARNING: don't run with debug turned on in production!
if PRODUCTION_ENV:
    DEBUG = False
else:
    DEBUG = True

#Set allowed hosts for prod/dev enviraonemnt
#If we are in production env
if PRODUCTION_ENV:
    ALLOWED_HOSTS = ["wikipaths.mybluemix.net", "wikipaths.org", "www.wikipaths.org", "learnmaps.net", "www.learnmaps.net"]
else: #non production env
    ALLOWED_HOSTS = ["*"]

#Safety stuff

#If we are in production env
if PRODUCTION_ENV:

    SECUREFLAG = False

    # Honor the 'X-Forwarded-Proto' header for request.is_secure()
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = SECUREFLAG
    SESSION_COOKIE_SECURE = SECUREFLAG
    CSRF_COOKIE_SECURE = SECUREFLAG

    if not SECUREFLAG:
        print("WARNING! SECURE FLAG IS TURNED OFF.")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wikipaths_server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wikipaths_server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases


if PRODUCTION_ENV:
    #Database credentials populate
    import dj_database_url
    DATABASES = {'default': dj_database_url.config()}
else: #non production env
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#By default Django will search static files inside a static folder inside each app folder
#collectstatic will also look for static files inside these places

#We can set folders out of any app folder to also search for static files with the variable below
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]

#Folder where collect static will gather all of the static files to serve
#This need another server to serv it
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

#URL where files will be served. Not the actual place
STATIC_URL = '/static/'

# #Static file directory inclusion
# #If we are in production env
# if PRODUCTION_ENV and True:
#     #Serve static files in the root static folder
    
# # else: #non production env
# #     #Serve on correspondent static folders


